#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - staging
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  
after_success:
  - 'if [ branch = 'staging' ]; then
      firebase deploy --token $FIREBASE_TOKEN;
    else
      echo 'master';
    fi' 

notifications:
  email:
    on_failure: change
    on_success: change